os: "linux"

services:
  - "postgresql"

language: "python"
python:
  - "3.7"

cache:
  pip: "true"

install:
  - "make install"

before_script:
  - "psql -U postgres -f ./schema.sql"

script:
  - "make compile"
  - "make lint"
  - "make test"

after_success:
  - "make report"
  - "bash <(curl -s https://codecov.io/bash)"
  - "npm i"
  - "npx serverless deploy -v"
