os: linux
dist: bionic

services:
  - postgresql

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - python -m compileall txtmap/ tests/
  - python -m flake8 --statistics txtmap/ tests/
  - python -m coverage run --source txtmap -m unittest discover -vb tests/

after_success:
  - python -m coverage report -m
  - bash <(curl -s https://codecov.io/bash)
