os: linux
dist: bionic

services:
  - postgresql

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  pip: true

install:
  - pip install requirements.txt

script:
  - python -m unittest discover -vb test || echo 'No tests :('
