os: linux
dist: bionic

services:
  - postgresql

language: python
python:
  - "3.7"
  - "3.8"

cache:
  pip: true

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -vb tests/ || echo 'No tests :('

deploy:
  provider: heroku
  strategy: api
  edge: true
  on: master
