service: txtmap


provider:
  name: aws
  stage: dev
  runtime: python3.7
  region: sa-east-1  # Sao Paulo
  versionFunctions: false
  logRetentionInDays: 3
  deploymentBucket: sls-deploy


package:
  include:
    - '!./**'
    - './txtmap/**'
    - './handler.py'
  exclude:
    - './**'


functions:
  function:
    description: Lambda that handles all WebSocket connections
    handler: handler.handler
    memorySize: 128
    timeout: 5

    layers:
      - arn:aws:lambda:sa-east-1:898466741470:layer:psycopg2-py37:1

    events:
      - websocket: $connect
      - websocket: $disconnect
      - websocket: $default

    environment:
      DB_URL: postgresql://postgres:${ssm:/db/pass}@${ssm:/db/host}:5432/txtmap


plugins:
  - serverless-python-requirements
