service: txtmap


provider:
  name: aws
  stage: dev
  runtime: python3.8
  region: sa-east-1  # Sao Paulo

functions:
  hello:
    handler: txtmap.handler
    memorySize: 128
    timeout: 10



resources:
  Resources:

